### ISSUE TITLE
Tryied in Linux

### ISSUE THREAD

**Issue by pando85** [carlos-menezes/g203-rs#1]
Hello and thanks for this package.

I wanted to try it in Linux but it gives an error:
I did:
```bash
» git clone git@github.com:carlos-menezes/g203-rs.git
Cloning into 'g203-rs'...
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (21/21), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 21 (delta 6), reused 21 (delta 6), pack-reused 0
Receiving objects: 100% (21/21), 7.72 KiB | 7.72 MiB/s, done.
Resolving deltas: 100% (6/6), done.
» cd g203-rs
» cargo build --release
warning: unused manifest key: package.author
    Updating crates.io index
  Downloaded colorchoice v1.0.1
  Downloaded is_terminal_polyfill v1.70.0
  Downloaded anstyle-query v1.0.3
  Downloaded anstyle v1.0.7
  Downloaded proc-macro2 v1.0.84
  Downloaded anstyle-parse v0.2.4
  Downloaded anstream v0.6.14
  Downloaded rusb v0.9.4
  Downloaded cc v1.0.98
  Downloaded syn v2.0.66
  Downloaded libusb1-sys v0.7.0
  Downloaded libc v0.2.155
  Downloaded 12 crates (1.6 MB) in 0.33s
   Compiling proc-macro2 v1.0.84
   Compiling pkg-config v0.3.30
   Compiling cc v1.0.98
   Compiling unicode-ident v1.0.12
   Compiling utf8parse v0.2.1
   Compiling libc v0.2.155
   Compiling colorchoice v1.0.1
   Compiling anstyle-query v1.0.3
   Compiling is_terminal_polyfill v1.70.0
   Compiling anstyle v1.0.7
   Compiling heck v0.5.0
   Compiling rusb v0.9.4
   Compiling strsim v0.11.1
   Compiling clap_lex v0.7.0
   Compiling anstyle-parse v0.2.4
   Compiling anstream v0.6.14
   Compiling clap_builder v4.5.2
   Compiling quote v1.0.36
   Compiling libusb1-sys v0.7.0
   Compiling syn v2.0.66
   Compiling clap_derive v4.5.4
   Compiling clap v4.5.4
   Compiling g203_rs v0.1.1 (/tmp/g203-rs)
    Finished `release` profile [optimized] target(s) in 3.83s
» ls
Cargo.lock  Cargo.toml  README.md  src  target
» ls target/release/g203ctl
target/release/g203ctl
» ./target/release/g203ctl
thread 'main' panicked at src/main.rs:74:40:
called `Result::unwrap()` on an `Err` value: NoDevice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
» ./target/release/g203ctl --help
thread 'main' panicked at src/main.rs:74:40:
called `Result::unwrap()` on an `Err` value: NoDevice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Additional info:
```bash
» lsusb | rg G203
Bus 003 Device 004: ID 046d:c084 Logitech, Inc. G203 Gaming Mouse
» uname -a
Linux XXXX 6.6.30-2-MANJARO #1 SMP PREEMPT_DYNAMIC Wed May  8 17:46:43 UTC 2024 x86_64 GNU/Linux
```

I can help you to debug it on Linux.

**Comment by carlos-menezes** [comment]
Hey!

The Product ID of your mouse is `0xC084` and not `0xC09D`. Can you change the value of the constant to match your Product ID and see if the error still occurs?

https://github.com/carlos-menezes/g203-rs/blob/905bf3eb051f36489e8e1e713de3f6f4f61ecdd9/src/lib.rs#L8

**Comment by pando85** [comment]
Done, and also ran it with sudo to find the device:
```bash
» sudo ./target/release/g203ctl --help
thread 'main' panicked at src/main.rs:74:40:
called `Result::unwrap()` on an `Err` value: Busy
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by carlos-menezes** [comment]
I think the error is related to the configuration. Can you remove `handle.set_active_configuration(CONFIGURATION_ID)?;` from `lib.rs` and retry?

**Comment by pando85** [comment]
Without that there are no errors in the output but nothing happens with the lights.

**Comment by carlos-menezes** [comment]
What command are you trying to run? The Prodigy model only supports three operations (`solid`, `cycle` and `breathe`).

**Comment by pando85** [comment]
I tried all, starting with solid. There is no output and no physical changes in the mouse.

**Comment by carlos-menezes** [comment]
Can you check if there are any outgoing USB data packets when the command is executed? You can use WireShark.

**Comment by pando85** [comment]
There is outgoing and ingoing traffic but I don't understand a shit  of this :S.
[g203ctl.pcapng.tar.gz](https://github.com/carlos-menezes/g203-rs/files/15459056/g203ctl.pcapng.tar.gz)
Those packages were generated using this command:
```bash
sudo ./target/release/g203ctl solid ff00ff
```

**Comment by carlos-menezes** [comment]
If you narrow the displayed packets with `usb.idProduct == 0xc084`, you'll see that you only have two outgoing packets of type `GET DESCRIPTOR`. It seems that the packets aren't being sent. Can you configure your mouse with [piper](https://github.com/libratbag/piper)?

**Comment by pando85** [comment]
piper works perfectly fine.

**Comment by carlos-menezes** [comment]
Can you checkout the branch `chore/fix-config` and try to run the command `cargo r solid ff0000`?

**Comment by pando85** [comment]
```
» cargo build --release
warning: unused manifest key: package.author
   Compiling proc-macro2 v1.0.84
   Compiling cc v1.0.98
   Compiling pkg-config v0.3.30
   Compiling unicode-ident v1.0.12
   Compiling utf8parse v0.2.1
   Compiling libc v0.2.155
   Compiling anstyle-query v1.0.3
   Compiling is_terminal_polyfill v1.70.0
   Compiling colorchoice v1.0.1
   Compiling anstyle v1.0.7
   Compiling heck v0.5.0
   Compiling clap_lex v0.7.0
   Compiling strsim v0.11.1
   Compiling rusb v0.9.4
   Compiling anstyle-parse v0.2.4
   Compiling anstream v0.6.14
   Compiling clap_builder v4.5.2
   Compiling quote v1.0.36
   Compiling libusb1-sys v0.7.0
   Compiling syn v2.0.66
   Compiling clap_derive v4.5.4
   Compiling clap v4.5.4
   Compiling g203_rs v0.1.1 (/tmp/g203-rs)
    Finished `release` profile [optimized] target(s) in 3.22s
» sudo ./target/release/g203ctl solid ff00ff
[sudo] password for agil:
thread 'main' panicked at src/main.rs:74:40:
called `Result::unwrap()` on an `Err` value: NoDevice
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by pando85** [comment]
Changing the `PRODUCT_ID` I get again:
```
» cargo build --release
warning: unused manifest key: package.author
   Compiling g203_rs v0.1.1 (/tmp/g203-rs)
    Finished `release` profile [optimized] target(s) in 0.65s
» sudo ./target/release/g203ctl solid ff00ff
thread 'main' panicked at src/main.rs:80:39:
called `Result::unwrap()` on an `Err` value: Busy
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
